name: bio-webapp
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - fastapi
  - uvicorn[standard]
  - gunicorn
  - samtools
  - bcftools
  - gatk4 # Or your preferred variant caller
