name: bio-webapp
channels:
  - conda-forge
  #  - bioconda
dependencies:
  - python
  - fastapi
  - uvicorn[standard]
  - gunicorn
  #  - samtools
  #  - bcftools
  #  - gatk4
  #  some components are disabled temporarily to ensure ligthweight container building process
